
-- 1. TABLA DE TRANSACCIONES (Se mantiene para auditoría histórica)
CREATE TABLE IF NOT EXISTS public.transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_account TEXT NOT NULL, -- UUID o Username del emisor
    to_account TEXT NOT NULL,   -- UUID o Username del receptor
    amount NUMERIC NOT NULL,
    concept TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- LIMPIEZA DE FUNCIONES ANTIGUAS PARA EVITAR CONFLICTOS
DROP FUNCTION IF EXISTS public.transferir_creditos_estudiante(TEXT, TEXT, TEXT[], NUMERIC, TEXT, TEXT);
DROP FUNCTION IF EXISTS public.transferencia_manual_admin(TEXT, TEXT, NUMERIC, TEXT, BOOLEAN);
DROP FUNCTION IF EXISTS public.transferencia_estudiante(TEXT, TEXT, NUMERIC, TEXT);

-- 2. FUNCIÓN RPC: transferir_creditos_estudiante
-- Transfiere créditos de lecciones aprobadas (Banco -> Estudiante)
CREATE OR REPLACE FUNCTION transferir_creditos_estudiante(
    p_estudiante_id TEXT,
    p_admin_id TEXT,
    p_lecciones_ids TEXT[],
    p_monto_total NUMERIC,
    p_username TEXT,
    p_concept TEXT
) RETURNS VOID AS $$
BEGIN
    -- Registrar la transacción en el historial
    INSERT INTO public.transactions (from_account, to_account, amount, concept)
    VALUES (p_admin_id, p_estudiante_id, p_monto_total, p_concept);

    -- Restar del balance del Admin (Banco) en la tabla USERS
    UPDATE public.users 
    SET balance = COALESCE(balance, 0) - p_monto_total 
    WHERE id::text = p_admin_id OR username = p_admin_id;
    
    -- Sumar al balance del Estudiante en la tabla USERS
    UPDATE public.users 
    SET balance = COALESCE(balance, 0) + p_monto_total 
    WHERE id::text = p_estudiante_id OR username = p_estudiante_id;

    -- Marcar lecciones como pagadas (usando cast a texto para compatibilidad con UUIDs)
    UPDATE public.student_lessons 
    SET credits_transfered = true 
    WHERE id::text = ANY(p_lecciones_ids);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 3. FUNCIÓN RPC: transferencia_manual_admin
-- Movimientos manuales realizados por el Admin (Ingresos o Egresos)
CREATE OR REPLACE FUNCTION transferencia_manual_admin(
    p_estudiante_id TEXT,
    p_admin_id TEXT,
    p_monto NUMERIC,
    p_concept TEXT,
    p_es_ingreso BOOLEAN
) RETURNS VOID AS $$
DECLARE
    v_from_id TEXT;
    v_to_id TEXT;
BEGIN
    IF p_es_ingreso THEN
        v_from_id := p_admin_id;
        v_to_id := p_estudiante_id;
        
        UPDATE public.users SET balance = COALESCE(balance, 0) - p_monto WHERE id::text = v_from_id OR username = v_from_id;
        UPDATE public.users SET balance = COALESCE(balance, 0) + p_monto WHERE id::text = v_to_id OR username = v_to_id;
    ELSE
        v_from_id := p_estudiante_id;
        v_to_id := p_admin_id;
        
        UPDATE public.users SET balance = COALESCE(balance, 0) - p_monto WHERE id::text = v_from_id OR username = v_from_id;
        UPDATE public.users SET balance = COALESCE(balance, 0) + p_monto WHERE id::text = v_to_id OR username = v_to_id;
    END IF;

    INSERT INTO public.transactions (from_account, to_account, amount, concept)
    VALUES (v_from_id, v_to_id, p_monto, p_concept);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 4. FUNCIÓN RPC: transferencia_estudiante
-- Transferencias directas entre estudiantes o hacia el banco
CREATE OR REPLACE FUNCTION transferencia_estudiante(
    p_from_id TEXT,
    p_to_id TEXT,
    p_monto NUMERIC,
    p_concept TEXT
) RETURNS VOID AS $$
BEGIN
    -- Verificar fondos suficientes
    IF (SELECT COALESCE(balance, 0) FROM public.users WHERE id::text = p_from_id OR username = p_from_id) < p_monto THEN
        RAISE EXCEPTION 'Fondos insuficientes en tu cuenta';
    END IF;

    -- Ejecutar movimiento
    UPDATE public.users 
    SET balance = COALESCE(balance, 0) - p_monto 
    WHERE id::text = p_from_id OR username = p_from_id;

    UPDATE public.users 
    SET balance = COALESCE(balance, 0) + p_monto 
    WHERE id::text = p_to_id OR username = p_to_id;

    -- Registrar en historial
    INSERT INTO public.transactions (from_account, to_account, amount, concept)
    VALUES (p_from_id, p_to_id, p_monto, p_concept);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- PERMISOS
GRANT EXECUTE ON FUNCTION transferir_creditos_estudiante(TEXT, TEXT, TEXT[], NUMERIC, TEXT, TEXT) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION transferencia_manual_admin(TEXT, TEXT, NUMERIC, TEXT, BOOLEAN) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION transferencia_estudiante(TEXT, TEXT, NUMERIC, TEXT) TO anon, authenticated, service_role;

-- 5. TABLA DE CURSOS (Antes Materias)
CREATE TABLE IF NOT EXISTS public.courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. TABLA DE CLASES (Antes Lecciones)
CREATE TABLE IF NOT EXISTS public.classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo TEXT NOT NULL,
    descripcion TEXT,
    course_id BIGINT REFERENCES public.courses(id) ON DELETE CASCADE,
    assigned_time_minutes INTEGER NOT NULL DEFAULT 30,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(titulo, course_id)
);

-- 7. TABLA DE TEMAS (Antes Microtemas)
CREATE TABLE IF NOT EXISTS public.topics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo TEXT NOT NULL,
    contenido TEXT,
    class_id BIGINT REFERENCES public.classes(id) ON DELETE CASCADE,
    order_index INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. TABLA DE PREGUNTAS
CREATE TABLE IF NOT EXISTS public.preguntas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id BIGINT REFERENCES public.topics(id) ON DELETE CASCADE,
    tipo TEXT NOT NULL CHECK (tipo IN ('multiple_choice', 'true_false', 'open')),
    pregunta TEXT NOT NULL,
    respuesta_correcta TEXT NOT NULL,
    explicacion TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. TABLA DE OPCIONES PARA PREGUNTAS DE OPCIÓN MÚLTIPLE
CREATE TABLE IF NOT EXISTS public.opciones_pregunta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pregunta_id BIGINT REFERENCES public.preguntas(id) ON DELETE CASCADE,
    opcion TEXT NOT NULL,
    es_correcta BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. TABLA DE INTENTOS DE EXAMEN
CREATE TABLE IF NOT EXISTS public.intentos_examen (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estudiante_id TEXT NOT NULL, -- UUID o Username
    class_id BIGINT REFERENCES public.classes(id) ON DELETE CASCADE,
    fecha_inicio TIMESTAMPTZ DEFAULT NOW(),
    fecha_fin TIMESTAMPTZ,
    calificacion NUMERIC,
    topics_covered INTEGER[], -- IDs of topics they actually studied
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 11. TABLA DE RESPUESTAS DEL ESTUDIANTE
CREATE TABLE IF NOT EXISTS public.respuestas_estudiante (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    intento_id BIGINT REFERENCES public.intentos_examen(id) ON DELETE CASCADE,
    pregunta_id BIGINT REFERENCES public.preguntas(id) ON DELETE CASCADE,
    respuesta TEXT NOT NULL,
    es_correcta BOOLEAN,
    score NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 12. TABLA DE PROGRESO DE LA CLASE DEL ESTUDIANTE (NUEVO)
CREATE TABLE IF NOT EXISTS public.student_class_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estudiante_id TEXT NOT NULL,
    class_id BIGINT REFERENCES public.classes(id) ON DELETE CASCADE,
    current_topic_id BIGINT REFERENCES public.topics(id),
    time_remaining_seconds INTEGER NOT NULL,
    is_in_penalty BOOLEAN DEFAULT FALSE,
    penalty_time_remaining_seconds INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(estudiante_id, class_id)
);

-- 13. TABLA DE CONFIGURACIONES (SETTINGS) (NUEVO)
CREATE TABLE IF NOT EXISTS public.settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Default setting for credit value
INSERT INTO public.settings (key, value) VALUES ('credit_value_mxn', '2') ON CONFLICT (key) DO NOTHING;

-- 14. TABLA DE HISTORIAL DE CHAT (NUEVO)
DROP TABLE IF EXISTS public.gemini_lessons CASCADE;

CREATE TABLE IF NOT EXISTS public.class_chat_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leccion_id BIGINT REFERENCES public.classes(id) ON DELETE CASCADE,
    estudiante_id TEXT NOT NULL,
    chat_history JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(leccion_id, estudiante_id)
);
